### ISSUE TITLE
Feature: Add an indication of if the hurdle was bet in the 'hurdle' column.

### ISSUE THREAD

**Issue by mgates** [alex/nyt-2020-election-scraper#156]
perhaps a colored background or a 🟢 / 🔴  icon

**Comment by frewsxcv** [comment]
+0 from me. i understand the want to do this, but because our datasource can be a little unreliable (mainly est. votes remaining) indicating with green could indicate a success or a prediction that may not actually be the case. sorta similar to why we closed https://github.com/alex/nyt-2020-election-scraper/pull/107

**Comment by mgates** [comment]
That makes sense, added https://github.com/alex/nyt-2020-election-scraper/pull/172 in case anyone wants it, though

**Comment by bojanrajkovic** [comment]
Per discussion, closing this, since it seems too much like "calling it."
