### ISSUE TITLE
Negative vote count - upstream data or display bug?

### ISSUE THREAD

**Issue by konklone** [alex/nyt-2020-election-scraper#292]
Seeing this:

![image](https://user-images.githubusercontent.com/4592/98419367-bfeae880-2039-11eb-8057-36e1a9b2322f.png)

**Comment by JulesDT** [comment]
Yes, this is due to upstream data. The NYT stream gives a `tot_exp_vote` for each county that we sum up to give the total estimated votes for the State. We then withdraw the number of votes casted. So the number of votes casted probably just went above the expectations

**Comment by alex** [comment]
The underlying cause here is that the votes remaining is computed by taking the _estimated_ number of total votes and subtracting the number of computed votes. Clearly the estimate was a bit low for whatever reason. We get both these numbers from NYT (who get them from Edison Research):

1) Hopefully NYT/Edison revises their estimates
2) Maybe we can render something better.

**Comment by MarvinGS** [comment]
Yeah, maybe never let the remaining Votes get negative so the needed Percentage can not be reversed.

![image](https://user-images.githubusercontent.com/1520824/98419925-5fce6380-2086-11eb-9e60-4a37feee6701.png)

**Comment by scottleibrand** [comment]
https://github.com/alex/nyt-2020-election-scraper/issues/290 is an error-handling side-effect of this.

**Comment by Lilith-NightRose** [comment]
Maybe as a temporary fix, have if the Votes Remaining and Percent Needed columns go to N/A, possibly with a link to this issue if the votes remaining go below zero.

**Comment by tahg** [comment]
It's made clear in multiple places the total votes remaining is an estimate, and going negative I think is less confusing than being constrained to 0. The hurdle column should just be listed as NA, as the current calculation makes no sense.
