### ISSUE TITLE
Hurdle will show over 100%.

### ISSUE THREAD

**Issue by eebasso** [alex/nyt-2020-election-scraper#376]
I think this is fine. But you might want to have cap on the maximum number displayed. Perhaps if the hurdle goes beyond 10, you could say >1000% or something. Or maybe do that when the hurdle reaches 1 and do ">100%"

Edit: perhaps I will create a pull request for this myself

**Comment by Grocel** [comment]
Yeah you also could just say X won, when stuff gets >100%, because there is no way to turn that around.

However given that the "Votes Remaining" seems to be very off from the real count, a >100% text would be more appropriate. Especially with Georgia running their "unknown/unknown votes left" thing for like days, like a broken installer program running into `NaN`-numbers.

**Comment by fractionalhare** [comment]
Going to close this; see my comment on the [PR](https://github.com/alex/nyt-2020-election-scraper/pull/377) you opened.
