### ISSUE TITLE
Light/Dark switch

### ISSUE THREAD

**Issue by macgibbons** [alex/nyt-2020-election-scraper#88]
Could we add a toggle just to inverse the background/text?

**Comment by alex** [comment]
Currently this respects your browser's "media preference".

**Comment by JonathanGrant** [comment]
How do I set this in chrome?

**Comment by thomasdesr** [comment]
Thanks! It'd definitely be helpful to have a button but for now now we're gonna let user's browser control the setting.

@JonathanGrant I think this is normally set in an OS config somewhere rather than in Chrome directly. These might help
* https://support.apple.com/en-us/HT208976
* https://blogs.windows.com/windowsexperience/2016/08/08/windows-10-tip-personalize-your-pc-by-enabling-the-dark-theme/
