### ISSUE TITLE
+/- change column

### ISSUE THREAD

**Issue by myronpeto** [alex/nyt-2020-election-scraper#94]
This is an awesome tool, thanks a ton for putting it together. :) If I could be so bold, would you be willing to add a column showing the gain/loss for a candidate for every change? You could make it the gain/loss for the candidate that is behind (but I'm agnostic on that front). I can calculate it in my head but it would be nice to see the exact number.

**Comment by joshuaiz** [comment]
+1 for this. The Change column should show whom the change was for.

**Comment by fractionalhare** [comment]
-1 on this. I can understand why it's being asked for, but the tool was originally designed to be pretty visually simple and in my opinion adding another column would contribute to visual clutter.

**Comment by bandtank** [comment]
+1 This would be very useful. Complaining about 'visual clutter' when the table isn't as useful as it could be is missing the point. Make it prettier and less useful or uglier and more useful - the latter is obviously better when people are looking at this page for information about an election that will be over in a few days. The data is not easily accessible to people who have trouble reading tables, which is at least 48% of the population based on current events.  Ba dum tssss.

**Comment by thomasdesr** [comment]
Hey folks! Something like this could definitely be useful.

Atm we don't have an obvious place for this since the feedback we've received so far is fairly supportive of maintaining our current tabular layout. If folks want to vote :+1: and :-1:  on the original comment we can look into reconsidering something like this if we either have some spare capacity or sufficient community support.

(Closing for now to get this off our dashboard)
